title = "James Olds"
baseurl = "https://blog.jamesolds.me/"
languageCode = "en-us"
theme = "simple"

[params]
    subtitle = "Tech, tools, and thoughts"

[params.social]
    resume = "/james-olds-resume.pdf"
    github = "oldsj"
    linkedin = "jamesrolds"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true

[taxonomies]
  tag = "tags"
  category = "categories"